package splab.ufcg.edu.br.trace.query.parser;


//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140611 (SVN rev 31)
// Wed Jul 30 16:03:51 BRT 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int QUERY = 36;
  public static final int STRING_LITERAL = 41;
  public static final int LBRACKET = 2;
  public static final int GE = 20;
  public static final int ARTIFACT = 38;
  public static final int LPAREN = 6;
  public static final int REQUIREMENT = 33;
  public static final int MINUS = 26;
  public static final int RPAREN = 7;
  public static final int NOT = 32;
  public static final int SEMICOLON = 14;
  public static final int AND = 30;
  public static final int LT = 25;
  public static final int RCOL = 5;
  public static final int TYPE = 35;
  public static final int OR = 31;
  public static final int SEMANTIC = 34;
  public static final int COMMA = 13;
  public static final int DIV = 28;
  public static final int DOUBLEDOT = 10;
  public static final int VIEW = 37;
  public static final int PLUS = 27;
  public static final int DOT = 12;
  public static final int LE = 21;
  public static final int EOF = 0;
  public static final int RBRACKET = 3;
  public static final int error = 1;
  public static final int PIPE = 8;
  public static final int NUMBER = 19;
  public static final int EQ = 23;
  public static final int NAME = 18;
  public static final int TIMES = 29;
  public static final int ARROW = 15;
  public static final int COLON = 11;
  public static final int NE = 22;
  public static final int LCOL = 4;
  public static final int STRING = 17;
  public static final int DOMAIN = 40;
  public static final int AT = 16;
  public static final int GT = 24;
  public static final int DOUBLECOLON = 9;
  public static final int RESULT = 39;
}

